### ISSUE TITLE
Bug: Forward/Backward breaks index

### ISSUE THREAD

**Issue by realAnzary** [Dustopheles/PySort#1]
If an animation is stopped, you can use the forward/backward btn to see each step. If you resume the animation with the start button after you used the forward/backward button, the indices get messed up and might break the sorting-algo.

![Capture](https://github.com/Dustopheles/PySort/assets/88819239/2fd3f024-9c9f-4ca9-b94a-b26d5d6a185f)

**Comment by realAnzary** [comment]
Any update on this @Dustopheles

**Comment by Dustopheles** [comment]
Caused by pressing pause button multiple times, fixed in last commit
